# Generated by Django 3.0.7 on 2020-12-07 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='packing_content',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity per pack'),
        ),
        migrations.AddField(
            model_name='article',
            name='packing_name',
            field=models.PositiveIntegerField(choices=[(0, 'default'), (10, 'box'), (11, 'set'), (20, 'pair'), (120, 'dozen'),], default=0),
        ),
        migrations.AddField(
            model_name='firstaidkititem',
            name='packing_content',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity per pack'),
        ),
        migrations.AddField(
            model_name='firstaidkititem',
            name='packing_name',
            field=models.PositiveIntegerField(choices=[(0, 'default'), (10, 'box'), (11, 'set'), (20, 'pair'), (120, 'dozen'),], default=0),
        ),
        migrations.AddField(
            model_name='medicine',
            name='packing_content',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity per pack'),
        ),
        migrations.AddField(
            model_name='medicine',
            name='packing_name',
            field=models.PositiveIntegerField(choices=[(0, 'default'), (10, 'box'), (11, 'set'), (20, 'pair'), (120, 'dozen'),], default=0),
        ),
    ]
