# Generated by Django 3.0.6 on 2020-05-10 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Requisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('reference', models.CharField(max_length=20, verbose_name='Reference')),
                ('date_of_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date of Creation')),
                ('requested_date', models.DateField(blank=True, null=True, verbose_name='Requested Date')),
                ('status', models.PositiveIntegerField(choices=[(0, 'Draft'), (1, 'Pending Approval'), (2, 'Approved'), (3, 'Quoted'), (4, 'Ordered'), (5, 'Partially Received'), (6, 'Fully Received'), (99, 'Cancelled')], verbose_name='Status')),
                ('instructions', models.TextField(blank=True, null=True, verbose_name='Instructions')),
                ('port_of_delivery', models.CharField(max_length=5, verbose_name='Port of Delivery')),
                ('item_type', models.PositiveIntegerField(verbose_name='Item Type')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('quantity', models.PositiveIntegerField()),
                ('additional', models.TextField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('requisition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.Requisition')),
            ],
        ),
    ]
