# Create the Windows 64 installer (MSYS2/Mingw64, cxFreeze, NSIS)

name: Build Windows 64 Installer

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    defaults:
        run:
          shell: msys2 {0}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Setup MSYS2/MingW64 environment
      - uses: msys2/setup-msys2@v2
          with:
          update: true
          install: >-
            git
            patch
            mingw-w64-x86_64-python-pip
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-python-cairo
            mingw-w64-x86_64-gobject-introspection
            mingw-w64-x86_64-python-pillow
            mingw-w64-x86_64-gnupg
            mingw-w64-x86-64-zlib
            mingw-w64-x86_64-gtk3
            mingw-w64-x86_64-make
            mingw-w64-x86_64-nsis
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Retrieve Pharmaship sources
      - uses: actions/checkout@v2
      # Prepare virtualenv and install python dependencies
      - name: Prepare Python environment
      - run: |
          virtualenv --system-site-packages venv
          venv/bin/python -m pip install -r requirements.txt
          venv/bin/python -m pip install winpath
          venv/bin/python -m pip install cx_Freeze
      # Patch CairoSVG and Weasyprint for freezing
      - name: Path CairoSVG and Weasyprint
      - run: |
          mingw32-make patch_cairosvg
          mingw32-make patch_weasyprint
      # Generate installer
      - name: Build installer
      - run: |
          mingw32-make win64
      # Upload the produced installer
      - name: Upload installer
      - uses: actions/upload-artifact@v2
        with:
          name: WindowsInstaller
          path: './bin/pharmaship_setup_x64.exe'
      
      
      
            
